name: 'Powerful Devs: Hack Together Project Submission Form'
description: "Share your project with us to get a digital badge and win prizes!"
title: "Project: <short description>"
body:
  - type: input
    id: name
    attributes:
      label: Project Name
      description: Name of your project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a short description of your solution. What does it do? What problems does it solve?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Technology & Languages
      description: Check any technologies and languages used for your solution.
      options:
        - label: Copilot Studio
          required: false
        - label: Power Apps
          required: false  
        - label: Power Automate
          required: false 
        - label: Power Pages
          required: false
        - label: AI Builder
          required: false
        - label: Microsoft Fabric/Power BI
          required: false
        - label: Microsoft 365
          required: false
        - label: Integrations with external systems
          required: false
        - label: Azure (e.g. Azure AI Foundry or Azure Functions)
          required: false
        - label: Microsoft 365 Agents SDK
          required: false
        - label: Power Fx
          required: false
        - label: C#
          required: false
        - label: TypeScript
          required: false
        - label: Python
          required: false
          
  - type: textarea
    id: question_1
    attributes:
      label: Scalability of your solution
      description: How would this solution scale?
    validations:
      required: true
  - type: textarea
    id: question_2
    attributes:
      label: Security of your solution
      description: How does this solution ensure security best practices?
    validations:
      required: true
  - type: textarea
    id: question_3
    attributes:
      label: AI-power of your solution
      description: How is this solution AI powered?
    validations:
      required: true
  - type: input
    id: url_repo
    attributes:
      label: Project Repository URL
      description: URL of the GitHub repo with your project
    validations:
      required: true
  - type: input
    id: url_setup
    attributes:
      label: Project Setup Instructions URL
      description: Direct URL of the written setup instructions for your project
    validations:
      required: true
  - type: input
    id: video
    attributes:
      label: Project video
      description: Provide a link to a short demo video of your project. This should be no longer than 8 minutes. Preference is to have the video uploaded to YouTube as an unlisted video so that our judging panel can review the video. If you cannot upload to YouTube, please make sure that your video is publicly available for our judges to access.
    validations:
      required: true
      required: true
  - type: input
    id: teammembers
    attributes:
      label: Team Members
      description: Comma-separated list of GitHub usernames for all who worked on this project
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Badge validation
      description: In order to receive your badge, please fill out the following form - [Badge validation form](https://aka.us11.list-manage.com/subscribe?u=b3df03dd2b64a3bc8a2a200e8&id=4a558f9e2b). Every member on the team must submit this form to receive a badge. If you do not submit this form, you will not receive a badge. Please check this box to confirm all team members have submitted the badge distribution form.
      options:
        - label: I verify that all of my team members have completed the badge validation form.
          required: true
  - type: checkboxes
    attributes:
       label: Survey Completion
       description: please fill out the powerful devs hack survey -  [Official Powerful Devs Hack Together feedback survey](https://aka.ms/Powerfuldevs/hack/survey). 
       options:
        - label: I verify that all of my team members have completed the Official Powerful Devs Hack Together feedback survey.
          required: true
